### PR TITLE
miniupnpd: Add ext_perform_stun=allow-filtered option

### PR DESCRIPTION
**Pull request by Headcrabed**
This commit partitally reverts back the default behavior which has been altered by 276db87ca093 ("miniunpnpd: Remove the ability to disable port forwarding for update_ext_ip_addr_from_stun function").

Allow failed STUN CGNAT filter check to be ignored by by setting ext_perform_stun=allow-filtered.

@miniupnp Sorry for bothering you again, but in previous PR we have changed default behavior of miniupnpd. This might break some users' configuration. So I have added back the default behavior and allowed ext_perform_stun to be set to allow-filtered in this PR.

### CODE REVIEW

**Comment by Headcrabed** [comment]
Seems compile error caused by 08212b19bd146758a76bde81298e84409221bc95
`
/usr/bin/ld: portinuse.o: in function `port_in_use':
portinuse.c:(.text+0x75): undefined reference to `proto_itoa'
`

**Comment by miniupnp** [comment]
> Seems compile error caused by [08212b1](https://github.com/miniupnp/miniupnp/commit/08212b19bd146758a76bde81298e84409221bc95) `` /usr/bin/ld: portinuse.o: in function `port_in_use': portinuse.c:(.text+0x75): undefined reference to `proto_itoa' ``

sorry. Fixed in bd5d341bb1090a9070ce01360b2bc6bb6a5888a5 and 9eebd2bf893e416deb56612b8a13d48883a579a3

**Comment by miniupnp** [comment]
cherry-picked : 1c847ce2f2bc87969bcbc3542f72015d98448904 / 3b3d2c05bf707750409d3091bcff5710a6f9da9f
